FitnessSite/FitnessSite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('items/', include('items.urls')),
    path('parts/', include('parts.urls')),
    path('admin/', admin.site.urls),
]

FitnessSite/items/urls.py
from django.urls import path
from . import views

app_name = "items"
urlpatterns = [
    # view
    path('', views.IndexView.as_view(), name="index"),
    path('<int:pk>', views.IndexView.as_view(), name="index_Part"),
    path('create', views.CreateView.as_view(), name="create"),
    path('detail/<int:pk>', views.DetailView.as_view(), name="detail"),

    # action
    path('insert', views.insert, name="insert"),
    path('update', views.update, name="update"),
]

FitnessSite/parts/urls.py
from django.urls import path
from . import views

app_name = "parts"
urlpatterns = [
    # view
    path('', views.IndexView.as_view(), name="index"),
    path('<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('create', views.CreateView.as_view(), name="create"),

    # action
    path('insert', views.insert, name='insert'),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('update/', views.update, name="update")
]

FitnessSite/dailyrecords/models.py
from django.db import models
from items.models import ActionItem
from datetime import datetime


# Create your models here.
class DailyItem(models.Model):
    actionItem = models.ForeignKey(
        ActionItem, models.SET_NULL, blank=False, null=True)
    recordDate = models.DateTimeField('記錄日期', default=datetime.today())
    repes = models.IntegerField('次數')
    sets = models.IntegerField('組數')

    def __str__(self):
        return self.recordDate + '：' + self.repes+'x'+self.sets


class ItemRecord(models.Model):
    dailyItem = models.ForeignKey(
        DailyItem, models.SET_NULL, blank=False, null=True)
    weigth = models.FloatField('重量')
    repes = models.IntegerField('次數', null=True)
    remark = models.CharField("備註", max_length=20)

FitnessSite/items/models.py
from django.db import models
from parts.models import Part

from datetime import datetime


class ActionItem(models.Model):
    part = models.ForeignKey(
        Part,
        models.SET_NULL,
        blank=False,
        null=True,)
    item_name = models.CharField(max_length=20, null=True)
    create_date = models.DateTimeField('建立日期', default=datetime.today())
    modify_date = models.DateTimeField('修改日期', default=datetime.today())

    def __str__(self):
        return self.item_name

FitnessSite/parts/models.py
from django.db import models
from datetime import datetime
# Create your models here.


class Part(models.Model):
    part_txt = models.CharField(
        max_length=10, default='', unique=True, null=False, )
    part_name = models.CharField(max_length=10, default='', null=True)
    create_date = models.DateTimeField('建立日期', default=datetime.today())
    modify_date = models.DateTimeField('修改日期', default=datetime.today())

    def __str__(self):
        return self.part_name

FitnessSite/dailyrecords/views.py
from django.shortcuts import render

# Create your views here.

FitnessSite/items/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from parts.models import Part
from .models import ActionItem

# Create your views here.


class IndexView(generic.ListView):
    template_name = "items/index.html"
    context_obj_name = "part_list"
    model = Part

    def get_queryset(self):
        return Part.objects.all()

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        part_pk = self.kwargs.get('pk')

        if part_pk:
            part = Part.objects.get(pk=part_pk)
            item_list = part.actionitem_set.all()
            context['item_list'] = item_list

        return context


class CreateView(generic.CreateView):
    "新增"
    model = ActionItem
    template_name = 'items/edit.html'

    def get_context_data(self, **kwargs):
        part_list = Part.objects.all()

        context = {
            "action": "items:insert",
            "item": ActionItem,
            "part_list": part_list
        }

        return context


class DetailView(generic.DetailView):
    model = ActionItem
    template_name = "items/edit.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        part_list = Part.objects.all()

        context['action'] = "items:update"
        context['part_list'] = part_list

        return context


def insert(request):
    part_pk = request.POST['part']
    # part = Part.objects.get(pk=part_pk)
    # item = ActionItem(part=part, item_name=request.POST['item_name'])
    # item.save()

    return HttpResponseRedirect(reverse('items:index_Part', args=(part_pk,)))


def update(request):
    return HttpResponseRedirect(reverse('items:index_Part', args=(part_pk,)))

FitnessSite/parts/views.py
from django.http import HttpResponsePermanentRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .form import PartForm

from .models import Part
from django.forms.models import modelform_factory

# Create your views here.


class IndexView(generic.ListView):
    template_name = 'parts/index.html'
    context_obj_name = "part_list"

    def get_queryset(self):
        return Part.objects.all()


class DetailView(generic.DetailView):
    "編輯"
    model = Part
    template_name = 'parts/edit.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'parts:update'
        return context


class CreateView(generic.CreateView):
    "新增"
    model = Part
    fields = ['part_txt', 'part_name']
    template_name = 'parts/edit.html'

    def get_context_data(self, **kwargs):
        context = {
            "action": "parts:insert",
            "part": Part
        }

        return context


def insert(request):

    part = Part(part_name=request.POST['part_name'],
                part_txt=request.POST['part_txt'])
    part.save()

    return HttpResponsePermanentRedirect(reverse('parts:index'))


def delete(request, pk):
    part = Part.objects.get(pk=pk)
    part.delete()

    return HttpResponsePermanentRedirect(reverse('parts:index'))


def update(request):
    pk = request.POST['part_pk']
    part = Part.objects.get(pk=pk)
    partForm = modelform_factory(Part, fields=("part_txt", "part_name"))

    part.part_name = request.POST['part_name']
    part.part_txt = request.POST['part_txt']

    part.save()

    return HttpResponsePermanentRedirect(reverse('parts:index'))

FitnessSite/items/templates/items/edit.html
<form name="itemForm" action="{% url action %}" method="POST">
    {% csrf_token %}
    <div>
        <label>部位：</label>
        <select id="part" name="part">
            <option value="">請選擇</option>
            {% for part in part_list %}
            <option value="{{part.pk}}" 
                {% if actionitem.part.pk == part.pk %}selected="selected"{% endif %}>
                {{part.part_name}}
            </option>
            {% endfor %}
        </select>
    </div>
    <div>
        <label>動作項目：</label>

        <input id="item_name" name="item_name" value="{{actionitem.item_name}}">
    </div>

    <button type="submit">送出</button>
    <button type="reset">清除</button>
</form>

FitnessSite/items/templates/items/index.html
{% load static %}
<script src="{% static 'items/js/items.js' %}"></script>
<button type="button" onclick="create()">新增項目</button>

{% if part_list %}
<ul>
    {% for part in part_list %}
    <li>
        <a href="{% url 'items:index_Part' part.pk %}">
            {{part.part_name}}
        </a>
    </li>
    {% endfor %}
</ul>
{% endif %}

{% if item_list %}
<ul>
    {% for item in item_list %}
    <li>
        <a href="{% url 'items:detail' item.pk %}">
            {{item.item_name}}
        </a>
    </li>
    {% endfor %}
</ul>
{% endif %}
<div id="displayItem">

</div>

FitnessSite/parts/templates/parts/edit.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'parts/style/style.css' %}">


{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}


<form name="partForm" action="{% url action %}" method="POST">
    {% csrf_token %}
    <div>
        <label>部位代號：</label>
        <input type="text" id="part_txt" name="part_txt" value="{{part.part_txt}}" />
    </div>
    <div>
        <label>部位名稱：</label>
        <input type="text" id="part_name" name="part_name" value="{{part.part_name}}" />
    </div>
    <div>
        <input type="hidden" id="part_pk" name="part_pk" value="{{part.pk}}" />
    </div>

    <div>
        <button type="submit">送出</button>
        <button type="reset">清除</button>
    </div>
</form>

FitnessSite/parts/templates/parts/formtest.html
{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form name="partForm" action="" method="POST">
    {% csrf_token %}
    <div>
        {{form.subject.errors}}
        <label for="{{form.subject.id_for_label}}">
            Email subject:
        </label>
        {{form.subject}}
    </div>

    <div>
        <button type="submit">送出</button>
    </div>
</form>

FitnessSite/parts/templates/parts/index.html
{% load static %}
<script src="{% static 'parts/js/parts.js' %}"></script>


<button onclick="create()">新增部位</button>
{% if part_list %}
<ul>
    {% for part in part_list %}
    <li>
        <a href="{% url 'parts:detail' part.pk %}">
            {{part.part_name}}
        </a>
        <a href="{% url 'parts:delete' part.pk %}">
            刪除
        </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>無部位資料</p>
{% endif %}